server:
  port: 8090

spring:
  application:
    name: voice-commerce-gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        # Auth Service Routes (Port 8084)
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/vcom/api/v1/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: authService
                fallbackUri: forward:/fallback/auth

        # Product Service Routes (Port 8085)
        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/vcom/api/v1/products/**, /vcom/api/v1/categories/**
          filters:
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: productService
                fallbackUri: forward:/fallback/product

        # Cart Service Routes (Port 8082)
        - id: cart-service
          uri: http://localhost:8082
          predicates:
            - Path=/vcom/api/v1/cart/**
          filters:
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: cartService
                fallbackUri: forward:/fallback/cart

        # Order Service Routes (Port 8081)
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/vcom/api/v1/orders/**
          filters:
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/fallback/order

        # Search Service Routes (Port 8080)
        - id: search-service
          uri: http://localhost:8080
          predicates:
            - Path=/vcom/api/v1/search/**
          filters:
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: searchService
                fallbackUri: forward:/fallback/search

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      authService:
        baseConfig: default
      productService:
        baseConfig: default
      cartService:
        baseConfig: default
      orderService:
        baseConfig: default
      searchService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

jwt:
  secret: ${JWT_SECRET:TmV3U2VjdXJlS2V5Rm9yVm9pY2VDb21tZXJjZUdhdGV3YXlXaXRoTWluaW11bTI1NkJpdHNGb3JITUFDU0hBMjU2QWxnb3JpdGht}
  expiration: 86400000 # 24 hours
